# Generated by Django 4.1.3 on 2022-11-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_orderline_cart_remove_orderline_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('delivering', 'Delivering'), ('finished', 'Finished')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_cost',
            field=models.FloatField(null=True),
        ),
    ]
