# Generated by Django 4.1.3 on 2022-11-21 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_image',
        ),
    ]
