# Generated by Django 4.1.3 on 2022-11-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nr_stars',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
