# Generated by Django 4.1.3 on 2022-11-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_product_nr_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='nr_stars',
            field=models.IntegerField(default=0),
        ),
    ]
